apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rails.fullname" . }}-db-migrate
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
spec:
  template:
    spec:
      imagePullSecrets:
        {{- toYaml .Values.image.secrets | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "{{ .Values.app.dbMigrateCommand }}"]
          envFrom:
            - configMapRef:
                name: {{ include "rails.fullname" . }}
            - secretRef:
                name: {{ include "rails.fullname" . }}
