apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "github-runner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "github-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "github-runner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: workdir
          hostPath:
            path: {{ .Values.runnerWorkdir }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "github-runner.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ACCESS_TOKEN
              value: {{ .Values.accessToken }}
            - name: ORG_RUNNER
              value: "true"
            - name: ORG_NAME
              value: {{ .Values.orgName }}
            - name: RUNNER_WORKDIR
              value: {{ .Values.runnerWorkdir }}
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
            - name: workdir
              mountPath: {{ .Values.runnerWorkdir }}
