{{- if .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "rails.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "rails.fullname" . }}-cert
  dnsNames:
    - {{ .Values.service.host | quote }}
  issuerRef:
    name: {{ .Values.ingress.tls.issuer.name }}
    kind: Issuer
    group: cert-manager.io
{{- end }}
