{{- if .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    email: {{ .Values.ingress.tls.issuer.acme_email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    email: {{ .Values.ingress.tls.issuer.acme_email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end }}
