apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rails.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-upgrade, pre-install
    helm.sh/hook-weight: "-2"
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
