apiVersion: v1
kind: Service
metadata:
  name: {{ include "rails.fullname" . }}
  labels:
    {{- include "rails.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: {{ .Values.app.component }}
  selector:
    {{- include "rails.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.app.component }}
